version: '3'

services:

  nginx:
    image: nginx:1.21
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"

  node1:
    image: nginx:1.21
    container_name: node1
    volumes:
      - ./node_1_index.html:/usr/share/nginx/html/index.html
    ports:
      - "80"

  node2:
    image: nginx:1.21
    container_name: node2
    volumes:
      - ./node_2_index.html:/usr/share/nginx/html/index.html
    ports:
      - "80"
